# Generated by Django 4.2 on 2025-02-20 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Инвентаризация', '0003_alter_compyuter_ipadresss_alter_compyuter_mac_adress'),
    ]

    operations = [
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('ip_address', models.GenericIPAddressField()),
                ('mac_address', models.CharField(max_length=17)),
                ('cpu_info', models.CharField(max_length=255)),
                ('ram_size', models.CharField(max_length=50)),
                ('hdd_size', models.CharField(max_length=50)),
                ('ssd_size', models.CharField(blank=True, max_length=50, null=True)),
                ('gpu_info', models.CharField(blank=True, max_length=255, null=True)),
                ('printer_info', models.CharField(blank=True, max_length=255, null=True)),
                ('scanner_info', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
