# Generated by Django 4.2 on 2025-02-20 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Инвентаризация', '0004_computer'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Computer',
            new_name='ComputerAgent',
        ),
    ]
