# Generated by Django 4.2 on 2025-02-25 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Инвентаризация', '0005_rename_computer_computeragent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compyuter',
            name='GPU',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Инвентаризация.gpu', verbose_name='Видеокарта'),
        ),
        migrations.AlterField(
            model_name='compyuter',
            name='RAM_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Инвентаризация.ramtype', verbose_name='Тип оперативки'),
        ),
        migrations.AlterField(
            model_name='compyuter',
            name='disk_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Инвентаризация.disktype', verbose_name='Тип диска'),
        ),
        migrations.AlterField(
            model_name='compyuter',
            name='model_webcam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Инвентаризация.modelwebcamera', verbose_name='Модель вебкамеры'),
        ),
        migrations.AlterField(
            model_name='compyuter',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to='signature/', verbose_name=''),
        ),
    ]
