# Generated by Django 4.2 on 2025-02-27 06:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Инвентаризация', '0006_alter_compyuter_gpu_alter_compyuter_ram_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compyuter',
            name='GPU',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Инвентаризация.gpu', verbose_name='Видеокарта'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='compyuter',
            name='addedUser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник'),
        ),
        migrations.AlterField(
            model_name='compyuter',
            name='ipadresss',
            field=models.CharField(default=1, max_length=255, verbose_name='IPv4 адрес'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='compyuter',
            name='mac_adress',
            field=models.CharField(default=1, max_length=255, verbose_name='Физический(MAC) адрес'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='compyuter',
            name='model_webcam',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Инвентаризация.modelwebcamera', verbose_name='Модель вебкамеры'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='compyuter',
            name='qr_image',
            field=models.ImageField(default=1, upload_to='qr_codes/', verbose_name='QR-код'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='compyuter',
            name='signature',
            field=models.ImageField(default=1, upload_to='signature/', verbose_name=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='compyuter',
            name='updatedUser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_computers', to=settings.AUTH_USER_MODEL, verbose_name='Изменил'),
        ),
    ]
