# Generated by Django 4.2 on 2025-02-27 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Инвентаризация', '0009_alter_compyuter_cpu_alter_compyuter_gpu_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compyuter',
            name='HDD',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Инвентаризация.hdd', verbose_name='Диск  HDD'),
        ),
        migrations.AlterField(
            model_name='compyuter',
            name='SSD',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Инвентаризация.ssd', verbose_name='Диск  SSD'),
        ),
        migrations.AlterField(
            model_name='compyuter',
            name='disk_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Инвентаризация.disktype', verbose_name='Тип диска'),
        ),
        migrations.AlterField(
            model_name='compyuter',
            name='model_webcam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Инвентаризация.modelwebcamera', verbose_name='Модель вебкамеры'),
        ),
        migrations.AlterField(
            model_name='compyuter',
            name='printer',
            field=models.ManyToManyField(related_name='printer', to='Инвентаризация.printer', verbose_name='Принтеры'),
        ),
        migrations.AlterField(
            model_name='compyuter',
            name='scaner',
            field=models.ManyToManyField(related_name='scaner', to='Инвентаризация.scaner', verbose_name='Сканеры'),
        ),
        migrations.AlterField(
            model_name='compyuter',
            name='type_webcamera',
            field=models.ManyToManyField(related_name='typeCamera', to='Инвентаризация.typewebcamera', verbose_name='Тип вебкамера'),
        ),
        migrations.AlterField(
            model_name='compyuter',
            name='warehouse_manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Инвентаризация.warehousemanager', verbose_name='Зав. склада'),
        ),
    ]
