# Generated by Django 4.2 on 2025-03-06 04:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Инвентаризация', '0010_alter_compyuter_hdd_alter_compyuter_ssd_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compyuter',
            name='signature',
        ),
        migrations.AlterField(
            model_name='compyuter',
            name='departament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Инвентаризация.department', verbose_name='Цех'),
        ),
        migrations.AlterField(
            model_name='compyuter',
            name='qr_image',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/', verbose_name='QR-код'),
        ),
    ]
