# Generated by Django 4.2 on 2025-03-07 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Инвентаризация', '0011_remove_compyuter_signature_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='compyuter',
            name='bg_image',
            field=models.ImageField(blank=True, default='back.jpg', null=True, upload_to='', verbose_name='QR-код'),
        ),
        migrations.AlterField(
            model_name='compyuter',
            name='printer',
            field=models.ManyToManyField(blank=True, related_name='printer', to='Инвентаризация.printer', verbose_name='Принтеры'),
        ),
        migrations.AlterField(
            model_name='compyuter',
            name='scaner',
            field=models.ManyToManyField(blank=True, related_name='scaner', to='Инвентаризация.scaner', verbose_name='Сканеры'),
        ),
        migrations.AlterField(
            model_name='compyuter',
            name='type_webcamera',
            field=models.ManyToManyField(blank=True, related_name='typeCamera', to='Инвентаризация.typewebcamera', verbose_name='Тип вебкамера'),
        ),
    ]
