# Generated by Django 4.2 on 2025-03-11 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Инвентаризация', '0015_programlicense_remove_program_license_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compyuter',
            name='model_webcam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Инвентаризация.modelwebcamera', verbose_name='Модель вебкамеры'),
        ),
    ]
