# Generated by Django 4.2 on 2025-03-11 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Инвентаризация', '0016_alter_compyuter_model_webcam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compyuter',
            name='type_monitor',
            field=models.ManyToManyField(blank=True, related_name='typeMonitor', to='Инвентаризация.monitor', verbose_name='Тип Монитора'),
        ),
    ]
