# Generated by Django 4.2 on 2025-03-11 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Инвентаризация', '0017_alter_compyuter_type_monitor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='programlicense',
            options={'verbose_name': 'Программа лицензии ', 'verbose_name_plural': 'Программа лицензии'},
        ),
    ]
