# Generated by Django 4.2 on 2025-03-13 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Инвентаризация', '0019_alter_program_license_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compyuter',
            name='program',
        ),
        migrations.AddField(
            model_name='compyuter',
            name='program',
            field=models.ManyToManyField(blank=True, to='Инвентаризация.program', verbose_name='Программы'),
        ),
    ]
