# Generated by Django 4.2 on 2025-03-18 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Инвентаризация', '0020_remove_compyuter_program_compyuter_program'),
    ]

    operations = [
        migrations.AddField(
            model_name='compyuter',
            name='internet',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Интернет'),
        ),
    ]
