# Generated by Django 4.2 on 2025-03-19 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Инвентаризация', '0021_compyuter_internet'),
    ]

    operations = [
        migrations.AddField(
            model_name='compyuter',
            name='OS',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='OS'),
        ),
        migrations.AlterField(
            model_name='compyuter',
            name='internet',
            field=models.BooleanField(default=False, verbose_name='Интернет'),
        ),
    ]
