# Generated by Django 4.2 on 2025-03-19 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Инвентаризация', '0023_os_alter_compyuter_os'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compyuter',
            name='GPU',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Инвентаризация.gpu', verbose_name='Видеокарта'),
        ),
    ]
