# Generated by Django 4.2 on 2025-03-20 02:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Инвентаризация', '0024_alter_compyuter_gpu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compyuter',
            name='CPU',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Инвентаризация.cpu', verbose_name='Процессор'),
        ),
        migrations.AlterField(
            model_name='compyuter',
            name='HDD',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Инвентаризация.hdd', verbose_name='Диск  HDD'),
        ),
        migrations.AlterField(
            model_name='compyuter',
            name='SSD',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Инвентаризация.ssd', verbose_name='Диск  SSD'),
        ),
        migrations.AlterField(
            model_name='compyuter',
            name='frequency',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Инвентаризация.frequency', verbose_name='Частота процессора'),
        ),
        migrations.AlterField(
            model_name='compyuter',
            name='generation',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Инвентаризация.generation', verbose_name='Поколение процессора'),
        ),
    ]
