# Generated by Django 4.2 on 2025-03-20 02:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Инвентаризация', '0025_alter_compyuter_cpu_alter_compyuter_hdd_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compyuter',
            name='CPU',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Инвентаризация.cpu', verbose_name='Процессор'),
        ),
        migrations.AlterField(
            model_name='compyuter',
            name='RAMSize',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Инвентаризация.ramsize', verbose_name='Размер оперативной памяти'),
        ),
        migrations.AlterField(
            model_name='compyuter',
            name='RAM_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Инвентаризация.ramtype', verbose_name='Тип оперативки'),
        ),
        migrations.AlterField(
            model_name='compyuter',
            name='addedUser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник'),
        ),
        migrations.AlterField(
            model_name='compyuter',
            name='departament',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Инвентаризация.department', verbose_name='Цех'),
        ),
        migrations.AlterField(
            model_name='compyuter',
            name='disk_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Инвентаризация.disktype', verbose_name='Тип диска'),
        ),
        migrations.AlterField(
            model_name='compyuter',
            name='frequency',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Инвентаризация.frequency', verbose_name='Частота процессора'),
        ),
        migrations.AlterField(
            model_name='compyuter',
            name='generation',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Инвентаризация.generation', verbose_name='Поколение процессора'),
        ),
        migrations.AlterField(
            model_name='compyuter',
            name='internet',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Интернет'),
        ),
        migrations.AlterField(
            model_name='compyuter',
            name='ipadresss',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='IPv4 адрес'),
        ),
        migrations.AlterField(
            model_name='compyuter',
            name='joinDate',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Дате'),
        ),
        migrations.AlterField(
            model_name='compyuter',
            name='mac_adress',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Физический(MAC) адрес'),
        ),
        migrations.AlterField(
            model_name='compyuter',
            name='motherboard',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Инвентаризация.motherboard', verbose_name='Производитель МП'),
        ),
        migrations.AlterField(
            model_name='compyuter',
            name='motherboard_model',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Инвентаризация.motherboardmodel', verbose_name='Модель МП'),
        ),
        migrations.AlterField(
            model_name='compyuter',
            name='printer',
            field=models.ManyToManyField(blank=True, null=True, related_name='printer', to='Инвентаризация.printer', verbose_name='Принтеры'),
        ),
        migrations.AlterField(
            model_name='compyuter',
            name='program',
            field=models.ManyToManyField(blank=True, null=True, to='Инвентаризация.program', verbose_name='Программы'),
        ),
        migrations.AlterField(
            model_name='compyuter',
            name='scaner',
            field=models.ManyToManyField(blank=True, null=True, related_name='scaner', to='Инвентаризация.scaner', verbose_name='Сканеры'),
        ),
        migrations.AlterField(
            model_name='compyuter',
            name='type_compyuter',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Инвентаризация.typecompyuter', verbose_name='Тип орг.техники'),
        ),
        migrations.AlterField(
            model_name='compyuter',
            name='type_monitor',
            field=models.ManyToManyField(blank=True, null=True, related_name='typeMonitor', to='Инвентаризация.monitor', verbose_name='Тип Монитора'),
        ),
        migrations.AlterField(
            model_name='compyuter',
            name='type_webcamera',
            field=models.ManyToManyField(blank=True, null=True, related_name='typeCamera', to='Инвентаризация.typewebcamera', verbose_name='Тип вебкамера'),
        ),
        migrations.AlterField(
            model_name='compyuter',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Дата изменения'),
        ),
        migrations.AlterField(
            model_name='compyuter',
            name='updatedUser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_computers', to=settings.AUTH_USER_MODEL, verbose_name='Изменил'),
        ),
        migrations.AlterField(
            model_name='compyuter',
            name='user',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='compyuter',
            name='warehouse_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Инвентаризация.warehousemanager', verbose_name='Зав. склада'),
        ),
    ]
