# Generated by Django 4.2 on 2025-03-20 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Инвентаризация', '0026_alter_compyuter_cpu_alter_compyuter_ramsize_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compyuter',
            name='qr_image',
            field=models.ImageField(blank=True, default='qr_codes/default.png', null=True, upload_to='qr_codes/', verbose_name='QR-код'),
        ),
    ]
