# Generated by Django 4.2 on 2025-03-20 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Инвентаризация', '0027_alter_compyuter_qr_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compyuter',
            name='OS',
        ),
    ]
