# Generated by Django 4.2 on 2025-03-20 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Инвентаризация', '0028_remove_compyuter_os'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compyuter',
            name='model_webcam',
        ),
        migrations.AddField(
            model_name='compyuter',
            name='model_webcam',
            field=models.ManyToManyField(blank=True, null=True, to='Инвентаризация.modelwebcamera', verbose_name='Модель вебкамеры'),
        ),
    ]
