# Generated by Django 4.2 on 2025-03-24 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Инвентаризация', '0029_remove_compyuter_model_webcam_compyuter_model_webcam'),
    ]

    operations = [
        migrations.CreateModel(
            name='MFO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'МФО ',
                'verbose_name_plural': '2.2 МФО',
            },
        ),
        migrations.AddField(
            model_name='compyuter',
            name='mfo',
            field=models.ManyToManyField(blank=True, null=True, related_name='mfo', to='Инвентаризация.mfo', verbose_name='МФО'),
        ),
    ]
