# Generated by Django 4.2 on 2025-03-25 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Инвентаризация', '0031_remove_compyuter_mfo_compyuter_mfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compyuter',
            name='mfo',
        ),
        migrations.AddField(
            model_name='compyuter',
            name='mfo',
            field=models.ManyToManyField(blank=True, null=True, related_name='mfo', to='Инвентаризация.scaner', verbose_name='МФУ'),
        ),
    ]
