# Generated by Django 4.2 on 2025-03-26 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Инвентаризация', '0033_historicalcompyuter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compyuter',
            name='mfo',
            field=models.ManyToManyField(blank=True, null=True, related_name='mfo', to='Инвентаризация.mfo', verbose_name='МФУ'),
        ),
    ]
